### ISSUE TITLE
Mac M1 Compatibility

### ISSUE THREAD

**Issue by LiChoi** [apogiatzis/docker-compose-livereloader#12]
Is docker-compose-livereloader compatible with Mac M1's? When I run this on my M1, I keep getting this error:

livereloader     | Traceback (most recent call last):
livereloader     |   File "main.py", line 5, in <module>
livereloader     |     reloader.start()
livereloader     |   File "/reloader/reloader.py", line 136, in start
livereloader     |     observer.start()
livereloader     |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/api.py", line 256, in start
livereloader     |     emitter.start()
livereloader     |   File "/usr/local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 93, in start
livereloader     |     self.on_thread_start()
livereloader     |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
livereloader     |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
livereloader     |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
livereloader     |     self._inotify = Inotify(path, recursive)
livereloader     |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 187, in __init__
livereloader     |     Inotify._raise_error()
livereloader     |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 437, in _raise_error
livereloader     |     raise OSError(err, os.strerror(err))
**livereloader     | OSError: [Errno 38] Function not implemented**
livereloader exited with code 1

**Comment by apogiatzis** [comment]
I haven't really tested it on M1 but from the stack trace above it seems that `watchdog` dependency is not compatible with M1. In effect, this is makes the reloader not compatible with M1 too.

Thanks for raising this, I will check if any updated versions of watchdog are compatible with M1.

**Comment by apogiatzis** [comment]
This has been fixed with PR #14
