### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Chaostheorie** [apogiatzis/docker-compose-livereloader#9]
Hey. Thank you for your work on this project. It has really helped me when working with docker and my own small app. I've recently been interested in using this code for one of my projects on GitLab, and was surprised to see no licence mentioned anywhere.
Since I intend to fork this repository down the line and make some modifications, such as combining with other images, I was wondering if there was any specific licence chosen for the source code.

Best regards, 
Cobalt

**Comment by apogiatzis** [comment]
The license is MIT so feel free to use it. I will add it to the repository. thanks for pointing that out!
